/* SPDX-License-Identifier: MIT
 *
 * m5load.c - M5LOAD.EFI: carry the pinned kimg into the window, check that the
 * firmware's map allows it, and hand the CPU over.
 *
 * Phase 3b, results/orin-native-port/20260909T1100Z/m5-design.md §3.3 steps
 * 1-10 (this file) and §3.3 steps 11-14 (m5load-head.S), with §13's decisions.
 *
 * Freestanding: no libc, no compiler builtins, no static initialiser that holds
 * an address (that would emit an absolute relocation and break §3.4 item 6).
 * Every zero-initialised object lives in .pool, because the linker script
 * refuses a .bss so that SizeOfImage and the file always agree.
 */

#include "efi-min.h"

/* Build constants. m5load-blob.S is generated by build-m5-loader.sh and holds
 * the payload plus these three values, so the T0 build and the board build
 * differ only in it (§3.4 item 8). */
extern const UINT64 m5_blob_len;        /* the payload's own byte count      */
extern const UINT64 m5_blob_crc32;      /* zlib.crc32 over those bytes       */
extern const UINT64 m5_blob_image_size; /* image_size from the arm64 header  */
extern UINT8 m5_blob_start[];

/* Layout symbols from m5load.lds. */
extern UINT8 m5_image_end[];

#define TARGET        0x80080000ull
#define WINDOW_START  0x80000000ull
#define WINDOW_END    0xBE000000ull
#define ZONE_START    0x272770000ull
#define ZONE_END      0x2727F0000ull
#define TCU_TX        0x0C168000ull
#define TEXT_OFFSET   0x80000ull
#define PAGE          0x1000ull

#define CON_NONE  0ull
#define CON_TCU   1ull
#define CON_PL011 2ull

#define MODE_JUMP     0ull
#define MODE_EBS_FAIL 1ull

void m5_con_latch(UINT64 base, UINT64 kind);
void m5_tramp(UINT64 target, UINT64 image_size, UINT64 fdt, UINT64 mode);
void m5_reset(void);

/* ---------------------------------------------------------------- console */

static CHAR16 m5_line[256] __attribute__((section(".pool")));

static EFI_SYSTEM_TABLE *m5_st __attribute__((section(".pool")));

static UINTN m5_strlen(const char *s)
{
	UINTN n = 0;
	while (s[n] != '\0')
		n++;
	return n;
}

/* Print one ASCII line through ConOut, appending CRLF. UEFI consoles want
 * UCS-2, so the conversion happens here and nowhere else. */
static void m5_out(const char *s)
{
	UINTN i = 0;

	while (s[i] != '\0' && i < (sizeof(m5_line) / sizeof(m5_line[0])) - 3) {
		m5_line[i] = (CHAR16)(UINT8)s[i];
		i++;
	}
	m5_line[i++] = (CHAR16)'\r';
	m5_line[i++] = (CHAR16)'\n';
	m5_line[i] = 0;
	m5_st->ConOut->OutputString(m5_st->ConOut, m5_line);
}

/* A tiny builder, so every token is assembled in one buffer and printed once.
 * No allocation, no formatting library. */
static char m5_buf[256] __attribute__((section(".pool")));
static UINTN m5_buf_n __attribute__((section(".pool")));

static void b_reset(void)
{
	m5_buf_n = 0;
	m5_buf[0] = '\0';
}

static void b_str(const char *s)
{
	UINTN i = 0;

	while (s[i] != '\0' && m5_buf_n < sizeof(m5_buf) - 1)
		m5_buf[m5_buf_n++] = s[i++];
	m5_buf[m5_buf_n] = '\0';
}

static void b_hex(UINT64 v)
{
	char tmp[17];
	int i = 16;

	tmp[16] = '\0';
	if (v == 0) {
		b_str("0");
		return;
	}
	while (v != 0 && i > 0) {
		UINT8 n = (UINT8)(v & 0xf);
		tmp[--i] = (char)(n < 10 ? ('0' + n) : ('a' + n - 10));
		v >>= 4;
	}
	b_str(&tmp[i]);
}

static void b_dec(UINT64 v)
{
	char tmp[21];
	int i = 20;

	tmp[20] = '\0';
	if (v == 0) {
		b_str("0");
		return;
	}
	while (v != 0 && i > 0) {
		tmp[--i] = (char)('0' + (v % 10));
		v /= 10;
	}
	b_str(&tmp[i]);
}

static void b_out(void)
{
	m5_out(m5_buf);
}

/* ---------------------------------------------------------------- system */

static UINT64 read_currentel(void)
{
	UINT64 v;

	__asm__ volatile("mrs %0, CurrentEL" : "=r"(v));
	return v >> 2;
}

static UINT64 read_ctr(void)
{
	UINT64 v;

	__asm__ volatile("mrs %0, ctr_el0" : "=r"(v));
	return v;
}

/* The target address stays opaque to the optimiser. Without the barrier, GCC
 * forms one pointer from the other and stores m5_blob_start - TARGET as a
 * literal, which is a link-time constant: it differs between link bases (the
 * defect gate item 6 exists to catch) and would be wrong at run time, because
 * the firmware loads the image wherever it likes. */
__attribute__((noinline)) static UINT8 *target_ptr(void)
{
	UINT64 t = TARGET;

	__asm__("" : "+r"(t));
	return (UINT8 *)t;
}

__attribute__((noinline)) static void m5_copy(UINT8 *dst, const UINT8 *src, UINT64 n)
{
	UINT64 i;

	for (i = 0; i < n; i++)
		dst[i] = src[i];
}

__attribute__((noinline)) static void m5_zero(UINT8 *dst, UINT64 n)
{
	UINT64 i;

	for (i = 0; i < n; i++)
		dst[i] = 0;
}

static int guid_eq(const EFI_GUID *a, const EFI_GUID *b)
{
	int i;

	if (a->Data1 != b->Data1 || a->Data2 != b->Data2 || a->Data3 != b->Data3)
		return 0;
	for (i = 0; i < 8; i++)
		if (a->Data4[i] != b->Data4[i])
			return 0;
	return 1;
}

/* ---------------------------------------------------------------- the FDT
 *
 * Just enough of a flattened device tree to (a) validate it and (b) choose the
 * post-exit console (§13 decision C). Big-endian cells, structure-block walk.
 */

#define FDT_BEGIN_NODE 1u
#define FDT_END_NODE   2u
#define FDT_PROP       3u
#define FDT_NOP        4u
#define FDT_END        9u

static UINT32 be32(const UINT8 *p)
{
	return ((UINT32)p[0] << 24) | ((UINT32)p[1] << 16) | ((UINT32)p[2] << 8) | (UINT32)p[3];
}

static UINT64 be_cells(const UINT8 *p, UINT32 cells)
{
	UINT64 v = 0;
	UINT32 i;

	for (i = 0; i < cells; i++)
		v = (v << 32) | be32(p + 4 * i);
	return v;
}

static int str_has(const char *hay, UINTN hay_len, const char *needle)
{
	UINTN nlen = m5_strlen(needle);
	UINTN i, j;

	if (nlen == 0 || hay_len < nlen)
		return 0;
	for (i = 0; i + nlen <= hay_len; i++) {
		for (j = 0; j < nlen; j++)
			if (hay[i + j] != needle[j])
				break;
		if (j == nlen)
			return 1;
	}
	return 0;
}

struct fdt_console {
	UINT64 base;
	UINT64 kind;
};

/* Walk the tree once. Sets *out to the TCU when the root compatible names
 * Tegra 234, otherwise to the first arm,pl011 node's first reg address. */
static void fdt_pick_console(const UINT8 *fdt, struct fdt_console *out)
{
	UINT32 off_struct = be32(fdt + 8);
	UINT32 off_strings = be32(fdt + 12);
	UINT32 size_struct = be32(fdt + 36);
	const UINT8 *p = fdt + off_struct;
	const UINT8 *end = p + size_struct;
	const char *strings = (const char *)(fdt + off_strings);
	UINT32 depth = 0;
	UINT32 addr_cells = 2;
	UINT32 is_pl011 = 0;
	UINT64 pending_reg = 0;
	UINT32 have_reg = 0;

	out->base = 0;
	out->kind = CON_NONE;

	while (p + 4 <= end) {
		UINT32 tok = be32(p);

		p += 4;
		if (tok == FDT_BEGIN_NODE) {
			const UINT8 *q = p;

			while (q < end && *q != '\0')
				q++;
			p = (const UINT8 *)(((UINT64)q + 4) & ~3ull);
			depth++;
			is_pl011 = 0;
			have_reg = 0;
			continue;
		}
		if (tok == FDT_END_NODE) {
			if (is_pl011 && have_reg && out->kind == CON_NONE) {
				out->base = pending_reg;
				out->kind = CON_PL011;
			}
			if (depth > 0)
				depth--;
			is_pl011 = 0;
			have_reg = 0;
			continue;
		}
		if (tok == FDT_PROP) {
			UINT32 len = be32(p);
			UINT32 nameoff = be32(p + 4);
			const UINT8 *val = p + 8;
			const char *name = strings + nameoff;

			p = (const UINT8 *)(((UINT64)val + len + 3) & ~3ull);

			if (depth == 1 && str_has(name, m5_strlen(name), "#address-cells") && len >= 4)
				addr_cells = be32(val);
			if (str_has(name, m5_strlen(name), "compatible")) {
				if (depth == 1 && str_has((const char *)val, len, "nvidia,tegra234")) {
					out->base = TCU_TX;
					out->kind = CON_TCU;
					return;
				}
				if (str_has((const char *)val, len, "arm,pl011"))
					is_pl011 = 1;
			}
			if (str_has(name, m5_strlen(name), "reg") && m5_strlen(name) == 3 &&
			    len >= 4 * addr_cells) {
				pending_reg = be_cells(val, addr_cells);
				have_reg = 1;
			}
			continue;
		}
		if (tok == FDT_NOP)
			continue;
		break;                          /* FDT_END, or something unknown */
	}
}

/* ---------------------------------------------------------------- the run */

/* Fixed-width rows, never an array of pointers. A pointer table would hold
 * absolute addresses, and the link at base 0 and the link at 0x100000 would
 * stop matching, which is exactly what §3.4 gate item 6 tests for. Indexing
 * this array costs one PC-relative address computation and no stored pointer. */
static const char m5_type_names[16][20] = {
	"Reserved", "LoaderCode", "LoaderData", "BootServicesCode",
	"BootServicesData", "RuntimeServicesCode", "RuntimeServicesData",
	"Conventional", "Unusable", "ACPIReclaim", "ACPINVS", "MMIO",
	"MMIOPort", "PalCode", "Persistent", "other",
};

static const char *type_name(UINT32 t)
{
	return m5_type_names[t < 15 ? t : 15];
}

static int window_type_ok(UINT32 t)
{
	return t == EfiLoaderCode || t == EfiLoaderData || t == EfiBootServicesCode ||
	       t == EfiBootServicesData || t == EfiConventionalMemory;
}

static int zone_type_ok(UINT32 t)
{
	return t == EfiReservedMemoryType || t == EfiLoaderCode || t == EfiLoaderData ||
	       t == EfiBootServicesCode || t == EfiBootServicesData ||
	       t == EfiConventionalMemory || t == EfiACPIReclaimMemory;
}

static void refuse(const char *rule)
{
	b_reset();
	b_str("M5L REFUSE ");
	b_str(rule);
	b_out();
}

EFI_STATUS m5_main(EFI_HANDLE image, EFI_SYSTEM_TABLE *st)
{
	EFI_BOOT_SERVICES *bs;
	EFI_GUID li_guid = EFI_LOADED_IMAGE_PROTOCOL_GUID;
	EFI_GUID dtb_guid = EFI_DTB_TABLE_GUID;
	EFI_LOADED_IMAGE_PROTOCOL *li = 0;
	EFI_MEMORY_DESCRIPTOR *map = 0;
	struct fdt_console con;
	const UINT8 *fdt = 0;
	UINT64 fdt_size = 0;
	UINT64 image_size;
	UINT64 pages;
	EFI_PHYSICAL_ADDRESS target = TARGET;
	UINTN map_size = 0, map_key = 0, desc_size = 0;
	UINT32 desc_ver = 0;
	UINT32 crc = 0;
	UINT64 el;
	UINTN i;
	int go = 0;
	int allocated = 0;
	EFI_STATUS s;

	m5_st = st;
	bs = st->BootServices;

	/* Step 1: which mode, and where the firmware put us (§13 decision F). */
	s = bs->HandleProtocol(image, &li_guid, (void **)&li);
	if (!EFI_ERROR(s) && li != 0 && li->LoadOptions != 0 && li->LoadOptionsSize >= 4) {
		CHAR16 *o = (CHAR16 *)li->LoadOptions;
		UINTN n = li->LoadOptionsSize / sizeof(CHAR16);
		UINTN k = 0;
		UINTN last = 0;

		/* Take the last whitespace-separated word; the Shell may put the
		 * image path first. Anything that is not "go" means check. */
		for (k = 0; k < n && o[k] != 0; k++)
			if (o[k] == (CHAR16)' ' || o[k] == (CHAR16)'\t')
				last = k + 1;
		if (n - last >= 2) {
			CHAR16 a = o[last], b = o[last + 1];

			if ((a == (CHAR16)'g' || a == (CHAR16)'G') &&
			    (b == (CHAR16)'o' || b == (CHAR16)'O')) {
				CHAR16 c = (last + 2 < n) ? o[last + 2] : 0;

				if (c == 0 || c == (CHAR16)' ' || c == (CHAR16)'\t' ||
				    c == (CHAR16)'\r' || c == (CHAR16)'\n')
					go = 1;
			}
		}
	}

	el = read_currentel();
	b_reset();
	b_str("M5L start mode=");
	b_str(go ? "go" : "check");
	b_str(" el=");
	b_dec(el);
	b_str(" ctr=");
	b_hex(read_ctr());
	b_str(" self=");
	b_hex(li ? (UINT64)li->ImageBase : 0);
	b_str("+");
	b_hex(li ? li->ImageSize : 0);
	b_out();

	/* Step 2: the device tree, and with it the post-exit console. */
	for (i = 0; i < st->NumberOfTableEntries; i++) {
		if (guid_eq(&st->ConfigurationTable[i].VendorGuid, &dtb_guid)) {
			fdt = (const UINT8 *)st->ConfigurationTable[i].VendorTable;
			break;
		}
	}
	if (fdt == 0 || be32(fdt) != 0xd00dfeedu) {
		refuse("fdt");
		return EFI_UNSUPPORTED;
	}
	fdt_size = be32(fdt + 4);
	if (fdt_size > (16ull << 20)) {
		refuse("fdt");
		return EFI_UNSUPPORTED;
	}
	b_reset();
	b_str("M5L fdt addr=");
	b_hex((UINT64)fdt);
	b_str(" size=");
	b_hex(fdt_size);
	b_out();

	fdt_pick_console(fdt, &con);
	m5_con_latch(con.base, con.kind);
	b_reset();
	b_str("M5L con kind=");
	b_str(con.kind == CON_TCU ? "tcu" : (con.kind == CON_PL011 ? "pl011" : "none"));
	b_str(" base=");
	b_hex(con.base);
	b_out();

	/* Step 3: the payload is the one the build embedded. */
	s = bs->CalculateCrc32(m5_blob_start, (UINTN)m5_blob_len, &crc);
	if (EFI_ERROR(s) || (UINT64)crc != m5_blob_crc32) {
		b_reset();
		b_str("M5L crc src=bad");
		b_out();
		refuse("crc src");
		return EFI_LOAD_ERROR;
	}
	m5_out("M5L crc src=ok");

	/* Step 4: it really is an arm64 image, and the one we sized for. */
	image_size = m5_blob_image_size;
	if (m5_blob_start[0x38] != 'A' || m5_blob_start[0x39] != 'R' ||
	    m5_blob_start[0x3a] != 'M' || m5_blob_start[0x3b] != 0x64 ||
	    *(volatile UINT64 *)(m5_blob_start + 8) != TEXT_OFFSET ||
	    *(volatile UINT64 *)(m5_blob_start + 16) != image_size) {
		refuse("kimg");
		return EFI_LOAD_ERROR;
	}

	/* Step 5: reserve the target before anything else can take it. */
	pages = (image_size + PAGE - 1) / PAGE;
	s = bs->AllocatePages(AllocateAddress, EfiLoaderData, (UINTN)pages, &target);
	if (EFI_ERROR(s)) {
		b_reset();
		b_str("M5L REFUSE alloc status=");
		b_hex((UINT64)s);
		b_out();
		/* The overlapping descriptors say why; print them below. */
	} else {
		allocated = 1;

		/* Step 6: copy, zero the tail past the file (§13 decision D),
		 * then read it back through the firmware's own CRC. */
		m5_copy(target_ptr(), m5_blob_start, m5_blob_len);
		if (image_size > m5_blob_len)
			m5_zero(target_ptr() + m5_blob_len, image_size - m5_blob_len);

		crc = 0;
		s = bs->CalculateCrc32(target_ptr(), (UINTN)m5_blob_len, &crc);
		if (EFI_ERROR(s) || (UINT64)crc != m5_blob_crc32) {
			m5_out("M5L crc dst=bad");
			refuse("crc dst");
			bs->FreePages(TARGET, (UINTN)pages);
			return EFI_LOAD_ERROR;
		}
		m5_out("M5L crc dst=ok");
	}

	/* Step 7: what the firmware thinks the window, the zone and the tree
	 * are. Every overlapping descriptor is printed, pass or refuse. */
	map_size = 0;
	s = bs->GetMemoryMap(&map_size, 0, &map_key, &desc_size, &desc_ver);
	map_size += 8 * desc_size;
	s = bs->AllocatePool(EfiLoaderData, map_size, (void **)&map);
	if (EFI_ERROR(s) || map == 0) {
		refuse("map");
		return EFI_LOAD_ERROR;
	}
	s = bs->GetMemoryMap(&map_size, map, &map_key, &desc_size, &desc_ver);
	if (EFI_ERROR(s)) {
		refuse("map");
		return EFI_LOAD_ERROR;
	}

	{
		UINT64 covered = WINDOW_START;
		int window_bad = 0, zone_bad = 0, fdt_bad = 0, zone_seen = 0;
		UINTN n = map_size / desc_size;
		UINTN pass;

		/* Two passes over the same buffer: print, then decide. The map is
		 * not sorted by address, so the window rule needs its own sweep. */
		for (i = 0; i < n; i++) {
			EFI_MEMORY_DESCRIPTOR *d =
				(EFI_MEMORY_DESCRIPTOR *)((UINT8 *)map + i * desc_size);
			UINT64 start = d->PhysicalStart;
			UINT64 stop = start + d->NumberOfPages * PAGE;
			int hits_window = start < WINDOW_END && stop > WINDOW_START;
			int hits_zone = start < ZONE_END && stop > ZONE_START;
			int hits_fdt = start < (UINT64)fdt + fdt_size && stop > (UINT64)fdt;

			if (!hits_window && !hits_zone && !hits_fdt)
				continue;
			b_reset();
			b_str("M5L map type=");
			b_str(type_name(d->Type));
			b_str(" start=");
			b_hex(start);
			b_str(" pages=");
			b_hex(d->NumberOfPages);
			b_str(" attr=");
			b_hex(d->Attribute);
			b_out();

			if (hits_zone) {
				zone_seen = 1;
				if (!zone_type_ok(d->Type))
					zone_bad = 1;
			}
		}

		/* Window: every byte must be covered by an allowed type. Sweep by
		 * repeatedly finding the descriptor that starts at or before the
		 * first uncovered byte. */
		for (pass = 0; pass < n + 1 && covered < WINDOW_END; pass++) {
			UINT64 best_stop = covered;
			UINT32 best_type = EFI_MAX_MEMORY_TYPE;

			for (i = 0; i < n; i++) {
				EFI_MEMORY_DESCRIPTOR *d =
					(EFI_MEMORY_DESCRIPTOR *)((UINT8 *)map + i * desc_size);
				UINT64 start = d->PhysicalStart;
				UINT64 stop = start + d->NumberOfPages * PAGE;

				if (start <= covered && stop > covered && stop > best_stop) {
					best_stop = stop;
					best_type = d->Type;
				}
			}
			if (best_stop == covered) {
				b_reset();
				b_str("M5L REFUSE window reason=gap at=");
				b_hex(covered);
				b_out();
				window_bad = 1;
				break;
			}
			if (!window_type_ok(best_type)) {
				b_reset();
				b_str("M5L REFUSE window reason=type at=");
				b_hex(covered);
				b_out();
				window_bad = 1;
				break;
			}
			covered = best_stop;
		}

		if ((UINT64)fdt < TARGET + image_size && (UINT64)fdt + fdt_size > TARGET)
			fdt_bad = 1;

		if (!allocated || window_bad || zone_bad || fdt_bad) {
			if (zone_bad)
				refuse("zone");
			else if (fdt_bad)
				refuse("fdt overlap");
			else if (!allocated)
				refuse("alloc");
			/* window already printed its own reason */
			bs->FreePool(map);
			if (allocated)
				bs->FreePages(TARGET, (UINTN)pages);
			return EFI_LOAD_ERROR;
		}
		(void)zone_seen;
	}

	/* Step 8: check stops here, having changed nothing. */
	if (!go) {
		m5_out("M5L CHECK PASS");
		bs->FreePool(map);
		bs->FreePages(TARGET, (UINTN)pages);
		return EFI_SUCCESS;
	}

	/* Step 9: go needs EL2, because the shim refuses anything else. */
	if (el != 2) {
		m5_out("M5L REFUSE el=1");
		bs->FreePool(map);
		bs->FreePages(TARGET, (UINTN)pages);
		return EFI_UNSUPPORTED;
	}
	m5_out("M5L GO");

	/* Step 10: the map key must be the one the firmware has right now, so
	 * nothing may run between GetMemoryMap and ExitBootServices. */
	for (i = 0; i < 4; i++) {
		map_size = 0;
		bs->GetMemoryMap(&map_size, 0, &map_key, &desc_size, &desc_ver);
		map_size += 8 * desc_size;
		if (EFI_ERROR(bs->AllocatePool(EfiLoaderData, map_size, (void **)&map)))
			break;
		if (EFI_ERROR(bs->GetMemoryMap(&map_size, map, &map_key, &desc_size, &desc_ver)))
			continue;
		s = bs->ExitBootServices(image, map_key);
		if (!EFI_ERROR(s)) {
			/* Steps 11-14 are in m5load-head.S and do not return. */
			m5_tramp(TARGET, image_size, (UINT64)fdt, MODE_JUMP);
		}
		if (s != EFI_INVALID_PARAMETER)
			break;
	}

	/* Four attempts, no exit: say so after taking the CPU, then reset. */
	m5_tramp(TARGET, image_size, (UINT64)fdt, MODE_EBS_FAIL);
	return EFI_LOAD_ERROR;
}
