#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# build-board.sh — build startup-t234-orin-nano.
#
# The board directory lives in this repo, but it has to be built inside the QNX
# BSP source tree, because that is where the startup library and the makefile
# machinery are. So this stages our directory into an extracted BSP tree and
# runs the BSP's own build there. Nothing from the BSP comes back: the built
# startup is an output, and the repo keeps only our sources.
#
#   BSP=/path/to/extracted/BSP_hyp-guest-arm_be-800_... ./build-board.sh
#
# The BSP tree is the hypervisor-guest-arm zip from the QNX download portal,
# extracted anywhere outside the repo. Its lib/ sources are Apache-2.0; its
# build system is the standard QNX recurse.mk/qrules.mk one.
#
# Order matters and is not obvious: the library must be built AND installed
# before the board, because the board needs headers that `make hinstall` alone
# does not produce (asmoff.def is generated by the library build proper).
set -euo pipefail

BOARD=t234-orin-nano
HERE="$(cd "$(dirname "$0")" && pwd)"
BSP="${BSP:-$HOME/orin-native-port-bsp}"
STARTUP="$BSP/src/hardware/startup"

[ -d "$STARTUP/lib" ] || {
	echo "no BSP startup tree at $STARTUP" >&2
	echo "set BSP=/path/to/extracted/BSP_hyp-guest-arm_be-800_*" >&2
	exit 1
}

# The toolchain needs QNX_HOST/QNX_TARGET and its own bin on PATH; qnxsdp-env
# normally sets them. Derive from QNX_BASE otherwise, and append rather than
# prepend, so the QNX bin directory's own cat/cp/mkdir cannot shadow the
# shell's.
if [ -z "${QNX_HOST:-}" ] || [ -z "${QNX_TARGET:-}" ]; then
	QNX_BASE="${QNX_BASE:-$HOME/qnx800}"
	[ -d "$QNX_BASE" ] || { echo "no SDP at $QNX_BASE — set QNX_BASE or source qnxsdp-env" >&2; exit 1; }
	qhost="$QNX_BASE/host/win64/x86_64"
	[ -d "$qhost" ] || qhost="$QNX_BASE/host/linux/x86_64"
	if command -v cygpath >/dev/null 2>&1; then
		export QNX_HOST="$(cygpath -w "$qhost")"
		export QNX_TARGET="$(cygpath -w "$QNX_BASE/target/qnx")"
	else
		export QNX_HOST="$qhost"
		export QNX_TARGET="$QNX_BASE/target/qnx"
	fi
	export PATH="$PATH:$qhost/usr/bin"
	# recurse.mk and qrules.mk are found through MAKEFLAGS, which qnxsdp-env
	# sets and which nothing else will.
	export MAKEFLAGS="-I$QNX_BASE/target/qnx/usr/include"
	echo "== using SDP at $QNX_BASE"
fi

# The library needs one change of its own: wait_for_rwp is an unbounded busy-wait
# on a bit the library itself flags as possibly never clearing, and a spin there
# cannot be recovered on this board. Applying it here rather than by hand keeps
# the built startup honest about what it contains. Idempotent.
GICH="$STARTUP/lib/public/aarch64/gic.h"
if [ -f "$GICH" ] && ! grep -q __rwp_limit "$GICH"; then
	echo "== bounding wait_for_rwp (patches/gic-bounded-rwp.patch)"
	if command -v git >/dev/null 2>&1 && git apply --directory="$(cd "$STARTUP/../../.." && pwd)" 	     "$HERE/patches/gic-bounded-rwp.patch" 2>/dev/null; then
		:
	else
		echo "   git apply did not take; patch it by hand or see the patch header" >&2
	fi
fi

echo "== staging $BOARD into the BSP tree"
rm -rf "${STARTUP:?}/boards/$BOARD"
mkdir -p "$STARTUP/boards/$BOARD"
cp -r "$HERE/$BOARD/." "$STARTUP/boards/$BOARD/"

# The library is built once and reused. It has to exist before the board, and
# not only for the archive: `make hinstall` alone leaves out asmoff.def, which
# the callout assembly includes, so the full install is what is wanted.
#
# On Windows this step is best run from a cmd shell that has sourced
# qnxsdp-env.bat. The BSP's install rule calls the SDK's own qnx_cp wrapper,
# which mangles its arguments under Git Bash and fails with "cp: missing file
# operand"; the compile and link steps are unaffected. Hence the skip below —
# once the library is in place, the board builds fine from either shell.
LIBA="$BSP/install/aarch64le/usr/lib/libstartup.a"
ASMOFF="$BSP/install/usr/include/aarch64/asmoff.def"
if [ -f "$LIBA" ] && [ -f "$ASMOFF" ]; then
	echo "== startup library already installed, reusing it"
else
	echo "== building the startup library (needed first: it generates asmoff.def)"
	if ! ( cd "$STARTUP/lib" && make install ); then
		echo "" >&2
		echo "The library install failed. On Windows, run this once from a cmd shell:" >&2
		echo "    call %USERPROFILE%\\qnx800\\qnxsdp-env.bat" >&2
		echo "    cd $STARTUP/lib && make install" >&2
		echo "then re-run this script." >&2
		exit 1
	fi
fi

echo "== building $BOARD"
( cd "$STARTUP/boards/$BOARD/aarch64/le" && make )

OUT="$STARTUP/boards/$BOARD/aarch64/le/startup-$BOARD"
[ -f "$OUT" ] || { echo "no output at $OUT" >&2; exit 1; }
echo "== built $OUT ($(stat -c %s "$OUT") bytes)"

echo "== symbol gate"
fail=0
for s in display_char_tcu poll_key_tcu break_detect_tcu init_tcu put_tcu \
         psci_smc psci_smp_start psci_cpu_id gic_v3_set_paddr_range \
         gic_v3_initialize hyp_enable_el2_host hypervisor_init \
         board_smp_start board_smp_num_cpu init_intrinfo cpuid_a78ae; do
	if ! ntoaarch64-nm "$OUT" | awk -v s="$s" '$NF==s' | grep -q .; then
		echo "  MISSING $s" >&2
		fail=1
	fi
done

# The board's psci_cpu_id must win over the library's. Archive order should see
# to that, but a link-order change would silently restore the wrong mapping and
# the only symptom would be two cores that never start.
n=$(ntoaarch64-nm "$OUT" | awk '$NF=="psci_cpu_id" && $(NF-1) ~ /[TtWD]/' | wc -l)
[ "$n" = "1" ] || { echo "  psci_cpu_id defined $n times, expected 1" >&2; fail=1; }

# No firmware-entry code should be linked in: this startup is entered from the
# shim, not from UEFI. The three uefi_*_f entries are weak hook pointers the
# library always carries, not code.
if ntoaarch64-nm "$OUT" | grep -iE " (efi_|acpi_)" | grep -q .; then
	echo "  EFI/ACPI code linked in, which this entry path never uses" >&2
	fail=1
fi

[ "$fail" = "0" ] && echo "  all checks passed"
exit "$fail"
